### ISSUE TITLE
RSS not useful

### ISSUE THREAD

**Issue by IRus** [talkingkotlin/website#1]
I know that Talking Kotlin has soundcloud RSS with recordings, but initially I found http://talkingkotlin.com/feed.xml, which doesn't contains recordings, and looks bad in reader. 

So I have suggestion:
Adjust http://talkingkotlin.com/feed.xml feed to contain enclosure with podcast recording.
Or use soundcloud feed in head https://github.com/talkingkotlin/website/blob/master/_includes/head.html#L28

**Comment by hhariri** [comment]
Done!
